backend:
  name: github
  repo: voldmar/pema

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: homepage
    label: Homepage
    files:
      - file: data/events.yml
        name: events
        label: Events
        fields:
          - label: Event
            name: event
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: When
                name: when
                widget: string
              - label: Where
                name: where
                widget: string
              - label: Type
                name: type
                widget: string
              - label: Registration
                name: registration
                widget: string
              - label: Description
                name: description
                widget: markdown
