backend:
  name: github
  repo: voldmar/pema
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: homepage
    title: Homepage
    files:
      - file: data/events.yml
        name: events
        label: Event
        fields:
          - label: Title
            name: title
            widget: string